description = "Ubuntu 22.04 Jammy Jellyfish base image with buildpacks for Java, Go, .NET Core, Node.js, Python, Apache HTTPD, NGINX and Procfile plus a fix to copy java native libraries to the runtime image"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/dotnet-core:0.46.0"
version = "0.46.0"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/go:4.8.0"
version = "4.8.0"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/java-native-image:9.6.0"
version = "9.6.0"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/java:15.0.0"
version = "15.0.0"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/nodejs:2.2.0"
version = "2.2.0"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/procfile:5.9.0"
version = "5.9.0"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/python:2.19.0"
version = "2.19.0"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/ruby:0.46.1"
version = "0.46.1"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/web-servers:0.23.0"
version = "0.23.0"

[[buildpacks]]
uri = "docker://fabiofalci/copy_native_lib_buildpack:0.0.1"
version = "0.0.1"

[lifecycle]
version = "0.19.7"

[[order]]

[[order.group]]
id = "paketo-buildpacks/ruby"
version = "0.46.1"

[[order]]

[[order.group]]
id = "paketo-buildpacks/dotnet-core"
version = "0.46.0"

[[order]]

[[order.group]]
id = "paketo-buildpacks/go"
version = "4.8.0"

[[order]]

[[order.group]]
id = "paketo-buildpacks/java-native-image"
version = "9.6.0"

[[order.group]]
id = "fabiofalci/copy_native_lib_buildpack"
version = "0.0.1"

[[order]]

[[order.group]]
id = "paketo-buildpacks/java"
version = "15.0.0"

[[order]]

[[order.group]]
id = "paketo-buildpacks/java"
version = "15.0.0"

[[order]]

[[order.group]]
id = "paketo-buildpacks/web-servers"
version = "0.23.0"

[[order]]

[[order.group]]
id = "paketo-buildpacks/nodejs"
version = "2.2.0"

[[order]]

[[order.group]]
id = "paketo-buildpacks/python"
version = "2.19.0"

[[order]]

[[order.group]]
id = "paketo-buildpacks/procfile"
version = "5.9.0"


# Base images used to create the builder
[build]
image = "docker.io/paketobuildpacks/build-jammy-base:0.1.117"
[run]
[[run.images]]
image = "index.docker.io/paketobuildpacks/run-jammy-base:latest"

[stack]
id = "io.buildpacks.stacks.jammy"
run-image-mirrors = []
